### ISSUE TITLE
Support JupyterLab 3.x

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/wxyz#42]
## Tasks
- [x] update dependencies
- [x] update locks
- [x] reorganize build
- [x] remove extra build steps
- [x] update robot tests
  - [x] ~~consider `robotframework-jupyterlibrary`~~
    - [ ]  moved to #53
- [x] update CI
- [x] update docs
  - [x] README 
  - [x] CHANGELOG
  - [x] CONTRIBUTING
- [x] validate binder
  - [x] with `bqplot` on page, etc. for `d3`  
  - [x] ~~with `jupyterlab-classic`~~
    - [x] moved to #52
- [x] tag
- [x] release
  - [x] pypi
  - [x] npm 
- [x] conda-forge
- [x] gh-pages 

## References

- [x] was blocked by https://github.com/deathbeds/jupyterlab-starters/issues/48
  - [x] https://pypi.org/project/jupyter-starters/1.0.0a0/#history
