### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/wxyz#44]
This is one of the last hold-outs on azure. Let's move it over to GHA before the Lab 3 push (#42).

- [x] #45 restored parity with azure
- [ ] #46 starts making some optimizations for file structure (keep/appease azure and gha)
- [ ] make `ci.yml` source of truth for lock creation, etc., update conda-lock behavior, remove azure 
- [ ] do better version validation, cut a 0.4.2 release to fix #47
