### ISSUE TITLE
Release 0.4.2

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/wxyz#48]
This is the last _planned_ JupyterLab 2-compatible release.

Notes:
- lays groundwork for pypi-distributable extensions on JupyterLab 3 (#42)

Tasks:
- [x] #45 migrate build/test infrastructure to github actions (for #44)
- [x] #46 unifies versions between python/javscript packages (for #47)
- [x] #49 turn off azure pipelines
  - [x] changelog
- [ ] ~~docs~~ no significant changes needed
- [x] tag
- [ ] publish
  - [x] pypi
  - [x] npm
  - [x] conda-forge https://github.com/conda-forge/jupyter-wxyz-feedstock/pull/1
